version: "3"

######## 项目依赖的环境，启动项目之前要先启动此环境 #######
######## The environment that the project depends on, starting this environment before starting the project #######

services:
  #zookeeper是kafka的依赖 - Zookeeper is the dependencies of Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    volumes:
      - ./data/zookeeper/data:/data
      - /etc/localtime:/etc/localtime
    restart: always
    ports:
      - 127.0.0.1:2181:2181
    networks:
      - telegram_net

  #消息队列 - Message queue
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 127.0.0.1:9092:9092
    environment:
      #TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Inbox-T:1:0,Sync-T:1:0"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    restart: always
    volumes:
      - ./data/kafka/data:/data
    networks:
      - telegram_net
    depends_on:
      - zookeeper

  etcd:
    image: quay.io/coreos/etcd:v3.5.2
    ports:
      - 127.0.0.1:2379:2379
      - 127.0.0.1:2380:2380
    container_name: etcd
    volumes:
      - ./data/etcd/data:/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime:ro
    environment:
      ETCDCTL_API: 3
      ETCD_DATA_DIR: /data
      ETCD_NAME: node1
      INITIAL_CLUSTER_TOKEN: etcd-test-cluster
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: node1=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_AUTO_COMPACTION_RETENTION: 1
    restart: always
    command: /usr/local/bin/etcd
    networks:
      - telegram_net

  redis:
    image: redis
    container_name: redis
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./data/redis/data:/data:rw
      #redis config file
      #- ./deploy/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Europe/Moscow
    restart: always
    privileged: true
    command: redis-server --appendonly yes
    networks:
      - telegram_net

  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    restart: on-failure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    container_name: postgres
    networks:
      - telegram_net

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - ./data/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorage
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - telegram_net

  minio_mc:
    image: minio/mc:latest
    container_name: minio_mc
    volumes:
      - ./minio_init.sh:/minio_init.sh
    entrypoint: /minio_init.sh
    networks:
      - telegram_net

networks:
  telegram_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16